version: "3.9"

networks:
  caesar_supervisor:
    external: true
    name: caesar_supervisor
  caesar_site:
    name: caesar_site_${SLUG}

volumes:
  wordpress:
  database:

services:
  # ---------------
  # MariaDB for the site install
  # - The Database
  # ---------------
  db:
    image: yobasystems/alpine-mariadb
    container_name: caesar-${SLUG}-db
    volumes:
      - database:/var/lib/mysql
    restart: unless-stopped
    networks:
      - caesar_site
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wp
      MYSQL_USER: wp
      MYSQL_PASSWORD: wp
  # ---------------
  # WordPress Container
  # - WP Core
  # ---------------
  wordpress:
    image: nextpress/caesar-wordpress:latest
    container_name: caesar-${SLUG}-wordpress
    depends_on:
      - caesar-${SLUG}-db
      - caesar-${SLUG}-cert
    networks:
      - caesar_supervisor
      - caesar_site
    volumes:
      - wordpress:/var/www/html
      - $LIB_PATH/mu-plugins/autoloader.php:/var/www/html/wp-content/mu-plugins/autoloader.php:ro
      - $LIB_PATH/mu-plugins/info.php:/var/www/html/wp-content/mu-plugins/info.php:ro
      - $LIB_PATH/scripts/container:/scripts
      # - $LIB_PATH/htaccess/.htaccess-single:/var/www/html/.htaccess-single
      # - $LIB_PATH/htaccess/.htaccess-subdir:/var/www/html/.htaccess-subdir
      # - $LIB_PATH/htaccess/.htaccess-subdomain:/var/www/html/.htaccess-subdomain
      - $CWD_PATH/plugins:/var/www/html/wp-content/plugins
      - $CWD_PATH/themes:/var/www/html/wp-content/themes
      - $CWD_PATH/mu-plugins:/var/www/html/wp-content/mu-plugins/files
      - $CWD_PATH/logs/xdebug:/logs/xdebug
    restart: unless-stopped
    environment:
      WORDPRESS_DB_HOST: caesar-${SLUG}-db
      WORDPRESS_DB_USER: wp
      WORDPRESS_DB_PASSWORD: wp
      WORDPRESS_DB_NAME: wp
      VIRTUAL_HOST: ${DOMAIN_NAME},${ADDITIONAL_DOMAIN_NAMES},${MAPPED_DOMAIN_NAMES}
      VIRTUAL_PORT: 80
  # ---------------
  # Cert Generator
  # - Generates SSL certs.
  # ---------------
  mkcert:
    image: nextpress/caesar-mkcert:latest
    container_name: caesar-${SLUG}-cert
    networks:
      - caesar_supervisor
    environment:
      DOMAIN: ${DOMAIN_NAME},${ADDITIONAL_DOMAIN_NAMES},${MAPPED_DOMAIN_NAMES}
    volumes:
      - ~/.caesar/certs:/certs
